src/objects/Billing_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Invoice on which this line item appears</description>
        <inlineHelpText>Invoice on which this line item appears</inlineHelpText>
        <label>Invoice</label>
        <referenceTo>RMA_Invoice__c</referenceTo>
        <relationshipLabel>Billing Line Items</relationshipLabel>
        <relationshipName>Billing_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <description>Project to which this line item is to be billed</description>
        <inlineHelpText>Project to which this line item is to be billed</inlineHelpText>
        <label>Project</label>
        <referenceTo>Appirio_PSAe__Proj__c</referenceTo>
        <relationshipLabel>Billing Line Items</relationshipLabel>
        <relationshipName>Billing_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Billing Line Item</label>
    <nameField>
        <displayFormat>BLI-{00000}</displayFormat>
        <label>Billing Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Invoice_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>RMA_Invoice__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Appirio_PSAe__Proj__c</referenceTo>
        <relationshipLabel>Invoice Line Items</relationshipLabel>
        <relationshipName>Invoice_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{0000}</displayFormat>
        <label>Invoice Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/RMA_Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Appirio_PSAe__Proj__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>Rainmaker Invoice-{00000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Work_Order__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>R00N30000002uhkVEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Budgeted_Hours__c</fullName>
        <defaultValue>&quot;1&quot;</defaultValue>
        <description>Quoted hours reflects the total development hours in the written quote (Shaffer and Cometto, i.e. sum of Dev Hours and Mgr Hours).  Project Management outside of Development are NOT INCLUDED.</description>
        <inlineHelpText>PM:  Add your hours to Quoted Hours for the total LOE to present to client.</inlineHelpText>
        <label>Quoted Hours</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>RMA Contact</inlineHelpText>
        <label>PM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00N30000002wNeLEAU</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>Appirio_PSAe__Proj__c</referenceTo>
        <relationshipLabel>Work Orders</relationshipLabel>
        <relationshipName>Work_Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>RFQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quoted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beta</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bug</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Technical_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Work_Orders1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Work Order</label>
    <nameField>
        <displayFormat>WO-{YYYY}{MM}-{00}</displayFormat>
        <label>Work Order Nu</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/testChangeProjectStatus.cls
public with sharing class testChangeProjectStatus {
	
	static testMethod void testChangeProjectStatus(){
		
		User userObj = Util.createUser();
		Account accObj = Util.createAccount();
		Appirio_PSAe__Resource__c resourceOBJ = Util.createResource(userObj.Id);
		Opportunity oppObj = Util.createOpportunity(accObj.id);
		Appirio_PSAe__Proj__c projectObj = Util.createProject(resourceOBJ.id, oppObj.Id, accObj.id);
		Appirio_PSAe__Assignment__c assign = Util.createAssignment(resourceOBJ.id,projectObj.id);
		Appirio_PSAe__Timecard__c timeObj = Util.createTimeCard(resourceOBJ.Id, projectObj.id, assign.id);
		
		// call 2 
		assign.Appirio_PSAe__Total_Assignment_Hours__c = 10;
		update assign;
		 
		try
		{
			Appirio_PSAe__Timecard__c timeObj2 = Util.createTimeCard(resourceOBJ.Id, projectObj.id, assign.id);
		}
		catch(Exception ex)
		{
			System.debug('Error On Insert....'+ex.getMessage());	
		}
		   
		
	}
	static testMethod void testCreateAssignmentbyWO() {
		
		System.debug('Trigger.ru onlce.....1....'+TriggerRunOnce.runOnce());
		
		User userObj = Util.createUser();
		Account accObj = Util.createAccount();
		Appirio_PSAe__Resource__c resourceOBJ = Util.createResource(userObj.Id);
		Opportunity oppObj = Util.createOpportunity(accObj.id);
		Appirio_PSAe__Proj__c projectObj = Util.createProject(resourceOBJ.id, oppObj.Id, accObj.id);
		Work_Order__c workObj = new Work_Order__c();
		workObj.Project__c = projectObj.id;
		workObj.Account__c = accObj.Id; 
		workObj.PM__c   = userObj.id; 
		workObj.Technical_Lead__c = userObj.id;
		workObj.Stage__c = 'Client Approved';
		workObj.Budgeted_Hours__c = '30';
		
		TriggerRunOnce.run = true;
		insert workObj; 
		System.debug('Trigger.ru onlce.....3....'+TriggerRunOnce.runOnce());
		
	}
	
	static testMethod void testCalculateBillingHours() {
		User userObj = Util.createUser();
		Account accObj = Util.createAccount();
		Appirio_PSAe__Resource__c resourceOBJ = Util.createResource(userObj.Id);
		Opportunity oppObj = Util.createOpportunity(accObj.id);
		Appirio_PSAe__Proj__c projectObj = Util.createProject(resourceOBJ.id, oppObj.Id, accObj.id);
		// add proj 
		Appirio_PSAe__Proj__c projectObj1 = Util.createProjectChild(resourceOBJ.id, oppObj.Id, accObj.id,projectObj.Id);
		
	}
	static testMethod void testTrackINvoiceDates() {
		User userObj = Util.createUser();
		Account accObj = Util.createAccount();
		Appirio_PSAe__Resource__c resourceOBJ = Util.createResource(userObj.Id);
		Opportunity oppObj = Util.createOpportunity(accObj.id);
		Appirio_PSAe__Proj__c projectObj = Util.createProject(resourceOBJ.id, oppObj.Id, accObj.id);
		 
		RMA_Invoice__c inVoiceOBj = new RMA_Invoice__c();
		inVoiceOBj.Project__c = projectObj.Id;
		inVoiceOBj.Account__c = accObj.Id; 
		inVoiceOBj.CurrencyIsoCode = 'USD';
		insert inVoiceOBj;
		
		Invoice_Line_Item__c lineOBj1 = new Invoice_Line_Item__c();
		lineOBj1.Invoice__c = inVoiceOBj.id;
		lineOBj1.Date__c = System.today();
		insert lineOBj1;
		
		Invoice_Line_Item__c lineOBj2 = new Invoice_Line_Item__c();
		lineOBj2.Invoice__c = inVoiceOBj.id;
		lineOBj2.Date__c = System.today().addDays(3);
		insert lineOBj2;
	}
	static testMethod void testChangeProjectonBuilling() {
		User userObj = Util.createUser();
		Account accObj = Util.createAccount();
		Appirio_PSAe__Resource__c resourceOBJ = Util.createResource(userObj.Id);
		Opportunity oppObj = Util.createOpportunity(accObj.id);
		Appirio_PSAe__Proj__c projectObj = Util.createProject(resourceOBJ.id, oppObj.Id, accObj.id);
		Billing_Line_Item__c billItem = Util.createBillLineItem(projectObj.Id);
		update billItem;
				
	}
	

}