src/objects/Escalation_Track__c.object
<CustomObject>
    <fields>
        <fullName>CaseLastModifiedBy__c</fullName>
        <description>This Will store the last modified case user&apos;s name  of the related case</description>
        <inlineHelpText>This Will store the last modified case user&apos;s name  of the related case</inlineHelpText>
        <label>CaseLastModifiedBy</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseLastModifiedDate__c</fullName>
        <label>CaseLastModifiedDate</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseType__c</fullName>
        <description>This Will store the type of the related case</description>
        <inlineHelpText>This Will store the type of the related case</inlineHelpText>
        <label>CaseType</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Account_Manager_Email__c</fullName>
        <description>Account manager email id of related case.</description>
        <label>Case Account Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Case_Engagement_Manager_Email__c</fullName>
        <description>Engagement manager email id of related case.</description>
        <label>Case Engagement Manager Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Case_Mail_Notification_Time__c</fullName>
        <description>Case Mail Notification Time</description>
        <inlineHelpText>Case Mail Notification Time</inlineHelpText>
        <label>Case Mail Notification Time</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Number__c</fullName>
        <description>Case Number</description>
        <label>Case Number</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Priority__c</fullName>
        <label>Case Priority</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case_Status__c</fullName>
        <label>Case Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Escalation Tracks</relationshipLabel>
        <relationshipName>Escalation_Tracks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Escalation Track</label>
    <nameField>
        <displayFormat>Escalation Track - {0000}</displayFormat>
        <label>Escalation Track Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalation Tracks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CaseEmailAlert.cls
/*******************************************************************************************************************
** Module Name   : CaseEmailAlert
** Description   : To call the function from the trigger "CaseEmailAlert"
** Throws        : NA
** Calls         : NA
** Test Class    : CaseEmailAlert_UnitTest
** 
** Organization  : Rain Maker
**
** Revision History:-
** Version             Date            Author           WO#         Description of Action
** 1.0                               Arun               Initial Version
******************************************************************************************************************/

public with sharing class CaseEmailAlert {
	public static Boolean isUpadted = false;
	
	
	// will save Escalation_Track__c record  if any update is not done on case object according to criteria
	public static Escalation_Track__c sendMail(Case lCaseObj, String mailNotificationTime)
	{
		system.debug('lCaseObj...'+lCaseObj + 'mailNotificationTime....' + mailNotificationTime);
		Escalation_Track__c escTrac = new Escalation_Track__c();
 		escTrac.Case__c = lCaseObj.id;
 		escTrac.CaseLastModifiedBy__c = string.valueof(lCaseObj.LastModifiedById);
 		escTrac.CaseLastModifiedDate__c = string.valueof(lCaseObj.LastModifiedDate);
 		escTrac.Case_Mail_Notification_Time__c = mailNotificationTime;
 		escTrac.CaseType__c = lCaseObj.Type;
 		escTrac.Case_Priority__c = lCaseObj.Priority;
 		escTrac.Case_Number__c = lCaseObj.CaseNumber;
 		escTrac.Case_Status__c = lCaseObj.Status;
 		escTrac.Case_Account_Manager_Email__c = lCaseObj.Account_Manager_Email__c;
 		escTrac.Case_Engagement_Manager_Email__c = lCaseObj.Engagement_Manager_Email__c;
 		system.debug('>>>>>>>>>Escalation_Track__c>>>>>>>'+ escTrac);         
        return escTrac;
	}
}