src/objects/GTMAccessToken__c.object
<CustomObject>
    <description>Hold GoTo Meeting Access Tokens</description>
    <fields>
        <fullName>Expiry_Date__c</fullName>
        <description>Expiry Date</description>
        <label>Expiry Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>GTMAccessToken</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ConnectToMeeting</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>GTMAccessToken Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ConnectToMeeting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/GTMConsoleExtension.cls
public with sharing class GTMConsoleExtension {

        public GTMConsoleExtension(Apexpages.StandardController controller) {
            showAlreadyExisting = false;
            GTMAccessToken__c workingToken;
            try {
                workingToken = [SELECT
                        GTMAccessToken__c.Id,
                        GTMAccessToken__c.User__c,                      
                        GTMAccessToken__c.Expiry_Date__c
                        FROM GTMAccessToken__c
                        WHERE GTMAccessToken__c.User__c =: System.Userinfo.getUserId() LIMIT 1];
               
                        //Indicate to the user that they already have valid information, but allow them to update
                        if (!(workingToken.Expiry_Date__c == null || workingToken.Expiry_Date__c < Datetime.now())) {
                                showAlreadyExisting = true;
                        }
        } catch(QueryException ex) {
            
                
        }
        }
        
        public Boolean showAlreadyExisting{get;set;}
}