src/objects/Login__c.object
<CustomObject>
    <description>Custom object to house Rainmaker login information</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N30000001Rp8zEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Login__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Primary Login</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sandbox_Login__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if these credentials are for a sandbox.</inlineHelpText>
        <label>Sandbox Login</label>
        <type>Checkbox</type>
    </fields>
    <label>Login</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/checkDuplicatePrimaryLogin_Test.cls
@isTest
Public class checkDuplicatePrimaryLogin_Test
{
    Static TestMethod void TestMethod_One()
    {
        Account Acc= new Account();
        Acc.name = 'Test';
        Acc.Industry_Sector__c = 'Association/NFP';
        Insert Acc;
        
        Login__c logObj = new Login__c();
        logObj.Name = 'TestLog';
        logObj.Account__c = Acc.id;
        logObj.Primary_Login__c = true;
        logObj.Sandbox_Login__c = true;
        try{
        insert logObj;
        }Catch(exception e){}
        
        Login__c logObj1 = new Login__c();
        logObj1.Name = 'TestLog1';
        logObj1.Account__c = Acc.id;
        logObj1.Primary_Login__c = true;
        logObj1.Sandbox_Login__c = true;
         try{
        insert logObj1;
        }Catch(exception e){}
        
        Login__c logObj2 = new Login__c();
        logObj2.Name = 'TestLog1';
        logObj2.Account__c = Acc.id;
        logObj2.Primary_Login__c = true;     
        logObj2.Sandbox_Login__c = false;    
        try{
        insert logObj2;
        }Catch(exception e){}
        
        Login__c logObj3 = new Login__c();
        logObj3.Name = 'TestLog1';
        logObj3.Account__c = Acc.id;
        logObj3.Primary_Login__c = true;     
        logObj3.Sandbox_Login__c = false;    
        try{
        insert logObj3;
        }Catch(exception e){}
        
        
        
    }
}