src/objects/Login__c.object
<CustomObject>
    <description>Custom object to house Rainmaker login information</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N30000001Rp8zEAC</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Login__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Primary Login</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sandbox_Login__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box if these credentials are for a sandbox.</inlineHelpText>
        <label>Sandbox Login</label>
        <type>Checkbox</type>
    </fields>
    <label>Login</label>
    <nameField>
        <label>Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logins</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/updateLogins_Test.cls
@isTest(SeeAllData = True)
public class updateLogins_Test
{
    Static TestMethod Void unittest()
    {
        Account Acc= new Account();
        Acc.name = 'Test';
        Acc.Industry_Sector__c = 'Association/NFP';
        Insert Acc;
        
        Login__c logObj = new Login__c();
        logObj.Name = 'TestLog';
        logObj.Account__c = Acc.id;
        logObj.Primary_Login__c = true;
        logObj.Sandbox_Login__c = true;
        try{insert logObj;}Catch(exception e){}
        
        Case cs= new Case();
        cs.AccountId = Acc.id;
        cs.Type = 'Problem' ;
        cs.Add_On__c = 'Basic Functionality';
        cs.Status = 'new';
        try{insert cs;}Catch(exception e){}            
    }        
    Static TestMethod Void unittest1()
    {
        Account Acc= new Account();
        Acc.name = 'Test';
        Acc.Industry_Sector__c = 'Association/NFP';
        Insert Acc;
        
        Login__c logObj = new Login__c();
        logObj.Name = 'TestLog';
        logObj.Account__c = Acc.id;
        logObj.Primary_Login__c = true;
        logObj.Sandbox_Login__c = False;
        try{insert logObj;}Catch(exception e){}
        
        Case cs= new Case();
        cs.AccountId = Acc.id;
        cs.Type = 'Problem' ;
        cs.Add_On__c = 'Basic Functionality';
        cs.Status = 'new';
        try{insert cs;}Catch(exception e){}            
    }      
    Static TestMethod Void unittest2()
    {
        Account Acc= new Account();
        Acc.name = 'Test';
        Acc.Industry_Sector__c = 'Association/NFP';
        Insert Acc;
        
        Login__c logObj = new Login__c();
        logObj.Name = 'TestLog';
        logObj.Account__c = Acc.id;
        logObj.Primary_Login__c = true;
        logObj.Sandbox_Login__c = False;
        try{insert logObj;}Catch(exception e){}
        
        Case cs= new Case();
        cs.AccountId = null;
        cs.Type = 'Problem' ;
        cs.Add_On__c = 'Basic Functionality';
        cs.Status = 'new';
        try{insert cs;}Catch(exception e){}            
    }        
}