src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <label>MPM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/batch_Milestone1Milestone.cls
/*******************************************************************************************************************
** Module Name   : batch_Milestone1Milestone
** Description   : batch class for "batch_Milestone1Milestone"
** Throws        : NA
** Calls         : NA
** Test Class    : batch_Milestone1Milestone_UnitTest
** 
** Organization  : Rain Maker
**
** Revision History:-
** Version             Date            Author           WO#         Description of Action
** 1.0                               Arun              
******************************************************************************************************************/
global class batch_Milestone1Milestone implements Database.Batchable<sObject>{
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator([SELECT Name, Deadline__c, Project__r.Account__r.Owner.Email, 
											Project__r.Owner.Email FROM Milestone1_Milestone__c ]); 
	}
	
	global void finish(Database.BatchableContext BC){
		//to do mail 
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){		
		String emailSubject = '';
		String emailBody = '';
		
		for(Sobject sobj : scope) {
			Milestone1_Milestone__c mileStoneObj = (Milestone1_Milestone__c)sobj;            
    		
    		String PMemail = mileStoneObj.Project__r.Owner.Email;
    		String EMemail = mileStoneObj.Project__r.Account__r.Owner.Email;
    		
	    	if(mileStoneObj != null && mileStoneObj.Deadline__c >= System.today() && (System.today().daysBetween(mileStoneObj.Deadline__c)) <= 5){
	        	String[] toaddress = new String[]{};					   	
	        	emailSubject = 'Milestone deadLine will be reached in ' + System.today().daysBetween(mileStoneObj.Deadline__c) + ' days.';
	        	emailBody = 'Milestone# ' + mileStoneObj.Name + ' DeadLine will be reached in ' + System.today().daysBetween(mileStoneObj.Deadline__c) + ' days.';
	        				
	        	if(PMemail != null && PMemail != ''){
	        		toaddress.add(PMemail);
	        	}
	        	if(EMemail != null && EMemail != ''){
	        		toaddress.add(EMemail);
	        	}
	        	if(!test.isRunningTest()){
	        		Util.sendEmail(emailSubject, emailBody, toaddress);
	        	}
	        }
        }
	}	
}