src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This signifies that this milestone has been completed.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <label>MPM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for completing the task. Defaults to current user if left blank.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks_Assigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>The date this task is due to be completed. Defaults to milestone due date if left blank.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/batch_Milestone1Task.cls
/*******************************************************************************************************************
** Module Name   : batch_Milestone1Task
** Description   : batch class for "batch_Milestone1Task"
** Throws        : NA
** Calls         : NA
** Test Class    : batch_Milestone1Task_UnitTest
** 
** Organization  : Rain Maker
**
** Revision History:-
** Version             Date            Author           WO#         Description of Action
** 1.0                               Arun              
******************************************************************************************************************/
global class batch_Milestone1Task implements Database.Batchable<sObject>{
	global Database.QueryLocator start(Database.BatchableContext BC) {
		if(test.isRunningTest()){
			return Database.getQueryLocator([SELECT Name, Assigned_To__c, Due_Date__c, Complete__c, Project_Milestone__r.Project__r.Owner.Email 
											FROM Milestone1_Task__c Limit 200]);
		}
		else{
			return Database.getQueryLocator([SELECT Name, Assigned_To__c, Due_Date__c, Complete__c, Project_Milestone__r.Project__r.Owner.Email 
											FROM Milestone1_Task__c ]);
		}		 
	}
	
	global void finish(Database.BatchableContext BC){
		//to do mail 
	}
	
	global void execute(Database.BatchableContext BC, List<sObject> scope){		
		String emailSubject = '';
		String emailBody = '';	
		Map<ID, String> userIdVsEmailMap = new Map<ID, String>();		
		List<User> userList = [SELECT Name, Email FROM User];
		for(User lUser: userList){
			if(lUser.Email != null && lUser.Email != ''){
				userIdVsEmailMap.put(lUser.ID, lUser.Email);			
			}			
		}		
		
		for(Sobject sobj : scope) {
			Milestone1_Task__c mileStoneTaskObj = (Milestone1_Task__c)sobj;            
            String PMemail = mileStoneTaskObj.Project_Milestone__r.Project__r.Owner.Email;
	    	String taskOwnerEmail = userIdVsEmailMap.get(mileStoneTaskObj.Assigned_To__c);
	    	   	
	    	if(mileStoneTaskObj != null && mileStoneTaskObj.Due_Date__c <= System.today() && !mileStoneTaskObj.Complete__c){
	        	String[] toaddress = new String[]{};					   	
	        	emailSubject = 'Task deadLine has been reached.';
	        	emailBody = 'Task# ' + mileStoneTaskObj.Name + ' DeadLine has been reached.';
	        				
	        	if(PMemail != null && PMemail != ''){
	        		toaddress.add(PMemail);
	        	}	        	
	        	if(!test.isRunningTest()){
        			Util.sendEmail(emailSubject, emailBody, toaddress);
	        	}
	        }
	        
	        if(mileStoneTaskObj != null && mileStoneTaskObj.Due_Date__c >= System.today() && (System.today().daysBetween(mileStoneTaskObj.Due_Date__c)) <= 5){
	        	String[] toaddress = new String[]{};					   	
	        	emailSubject = 'Task deadLine will be reached in '+ System.today().daysBetween(mileStoneTaskObj.Due_Date__c) + ' days.';
	        	emailBody = 'Task# ' + mileStoneTaskObj.Name + ' DeadLine will be reached in ' + System.today().daysBetween(mileStoneTaskObj.Due_Date__c) + ' days.';
	        				
	        	if(PMemail != null && PMemail != ''){
	        		toaddress.add(PMemail);
	        	}
	        	if(taskOwnerEmail != null && taskOwnerEmail != ''){
	        		toaddress.add(taskOwnerEmail);
	        	}	        	
	        	Util.sendEmail(emailSubject, emailBody, toaddress);
	        }
        }
	}
	
}