src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This signifies that this milestone has been completed.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A general description of the milestone.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expense_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The expense budget for the milestone.</inlineHelpText>
        <label>Milestone Expense Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The hours budget for the milestone.</inlineHelpText>
        <label>Milestone Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>When should this milestone kickoff?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The parent milestone for this milestone if applicable.</inlineHelpText>
        <label>Parent Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Child Milestones</relationshipLabel>
        <relationshipName>Child_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Expense_Budget__c</fullName>
        <formula>Expense_Budget__c +  Expense_Budget_from_Sub_Milestones__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated as expense budget + expense budget from sub milestones</inlineHelpText>
        <label>Total Expense Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Budget__c</fullName>
        <formula>Hours_Budget__c + Hours_Budget_from_Sub_Milestones__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated as hours budget + hours budget from sub milestones</inlineHelpText>
        <label>Total Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A general description of the project.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>What date should this project start?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The current status of the project.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Expense_Budget__c</fullName>
        <inlineHelpText>The total expense budget for this project.</inlineHelpText>
        <label>Total Expense Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Budget__c</fullName>
        <inlineHelpText>The total hours budget for this project.</inlineHelpText>
        <label>Total Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>MPM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The user responsible for completing the task. Defaults to current user if left blank.</inlineHelpText>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Project_Tasks_Assigned</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Blocked_Reason__c</fullName>
        <inlineHelpText>If blocked, why?</inlineHelpText>
        <label>Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this task blocked for some reason?</inlineHelpText>
        <label>Blocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Class__c</fullName>
        <inlineHelpText>Classify this task as appropriate for your use.</inlineHelpText>
        <label>Class</label>
        <picklist>
            <picklistValues>
                <fullName>Ad Hoc</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Defect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rework</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>The status of this task. A task is either in-complete or complete.</inlineHelpText>
        <label>Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>The general description of the task. For example, what is the purpose of the task.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <inlineHelpText>The date this task is due to be completed. Defaults to milestone due date if left blank.</inlineHelpText>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimated_Expense__c</fullName>
        <inlineHelpText>The estimated amount of expenses which will be incurred during the task.</inlineHelpText>
        <label>Estimated Expense</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Hours__c</fullName>
        <inlineHelpText>The estimated time to complete the task.</inlineHelpText>
        <label>Estimated Hours</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Email_Received__c</fullName>
        <description>Date Time the last email was sent to this task.</description>
        <inlineHelpText>The date the last email was attached to this task. A task can be created via an email, and additional emails can be attached to the task in the notes section.</inlineHelpText>
        <label>Last Email Received</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <inlineHelpText>This is the priority of the task. 0,1,2,3 or 4.</inlineHelpText>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>0</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <inlineHelpText>When should this task start by?</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Task_Stage__c</fullName>
        <inlineHelpText>Where is this task on the road to completion?</inlineHelpText>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>User_Story__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User Story</label>
        <referenceTo>User_Story__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User_Story__c.object
<CustomObject>
    <description>Feature Request is used for developing requirements.  The requirements would be in the form of user stories and defects and Test Cases can be tagged along with the feature requests</description>
    <fields>
        <fullName>Blocked_Reason__c</fullName>
        <label>Blocked Reason</label>
        <length>600</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Blocked__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Blocked</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Estimated_Hours__c</fullName>
        <label>Estimated Hours</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Milestone1_Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>User Stories (Milestone)</relationshipLabel>
        <relationshipName>User_Stories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Milestone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipName>Feature_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the feature request</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>RFQ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quoted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Client Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready to Test</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package Validated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>User Story</label>
    <nameField>
        <displayFormat>FR-{00000000}</displayFormat>
        <label>Feature Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Milestone1_Clone_Project_Controller.cls
/* 
Copyright (c) 2011, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, 
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, 
    this list of conditions and the following disclaimer. 
    * Redistributions in binary form must reproduce the above copyright notice, 
    this list of conditions and the following disclaimer in the documentation 
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors 
    may be used to endorse or promote products derived from this software 
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND 
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. 
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, 
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, 
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, 
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF 
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE 
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED 
OF THE POSSIBILITY OF SUCH DAMAGE.

*/
public with sharing class Milestone1_Clone_Project_Controller {
    
    public Milestone1_Project__c rec {get; set;}
    public Milestone1_Project__c dummyProj {get; set;}
    private List<Milestone1_Milestone__c> milestones {get; set;}
    private List<Milestone1_Task__c> tasks {get; set;}
    private List<User> statusList{get; set;}
    public Boolean isProjOwnerActive{get;set;}
    public boolean isInactiveUserToBeReplaced{get;set;}
    
    public Milestone1_Clone_Project_Controller(ApexPages.StandardController stc){
        //query project record
        rec = [SELECT Id,
                      Name,
                      Deadline__c,
                      Description__c,
                      Status__c,
                      Total_Expense_Budget__c,
                      Total_Hours_Budget__c,
                      KickOff__c,
                      OwnerId                      
               FROM Milestone1_Project__c
               WHERE Id = :stc.getId()
              ];        
        
        //query milestone records
        milestones = [SELECT Id,
                             Name,
                             Parent_Milestone__c,
                             Complete__c,
                             Deadline__c,
                             Description__c,
                             Expense_Budget__c,
                             Hours_Budget__c,
                             OwnerId,
                             KickOff__c
                      FROM Milestone1_Milestone__c
                      WHERE Project__c = :rec.Id
                     ];
        
        //query task records 
        tasks = [SELECT Id,
                        Name,
                        Project_Milestone__c,
                        User_Story__c,
                        Assigned_To__c,
                        Complete__c,
                        Description__c,
                        Start_Date__c,
                        Due_Date__c,
                        Priority__c,
                        Task_Stage__c,
                        Class__c,
                        Blocked__c,
                        Blocked_Reason__c,
                        Last_Email_Received__c,
                        Estimated_Hours__c,
                        Estimated_Expense__c
                 FROM Milestone1_Task__c
                 WHERE Project_Milestone__r.Project__c = :rec.Id
                ];
                
        dummyProj = new Milestone1_Project__c();
        dummyProj.Name = 'Copy of ' + rec.Name;      
        statusList = [SELECT IsActive from User where id = :rec.OwnerId];
        if(statusList  != null && statusList.size() > 0 )
            isProjOwnerActive = statusList[0].IsActive;
    }
    
    public PageReference createClone(){      
        Savepoint preSave = Database.setSavepoint(); //set savepoint so we can rollback the whole save if there are errors
        PageReference pageReference = null;
        try{
            
          if(isProjOwnerActive == false){
                if(dummyProj.OwnerId == null){
                   ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.ERROR,system.label.Milestone1_InactiveUsersError);
                   ApexPages.addMessage(myMsg);
                   isInactiveUserToBeReplaced = true;
                   return pageReference;
                }if(dummyProj.OwnerId != null){
                    rec.ownerId = dummyProj.OwnerId;                 
                }
            }             
            
            //create new project record
            rec.Name = dummyProj.Name;
            
            Milestone1_Project__c newProj = Milestone1_Clone_Utility.cloneProject(rec);
            insert newProj;
            //separate milestone records into parents and subs
            List<Milestone1_Milestone__c> topMilestones = new List<Milestone1_Milestone__c>();
            List<Milestone1_Milestone__c> bottomMilestones = new List<Milestone1_Milestone__c>();
            for(Milestone1_Milestone__c oldMS : milestones){
                if(oldMS.Parent_Milestone__c == null){
                    topMilestones.add(oldMS);
                } else {
                    bottomMilestones.add(oldMS);
                }
            }            
            //clone and insert top milestone records
            Map<String, Milestone1_Milestone__c> newTopMilestoneMap = Milestone1_Clone_Utility.cloneMilestonesIntoMap(topMilestones);
            for(Milestone1_Milestone__c newMS : newTopMilestoneMap.values()){
                newMS.Project__c = newProj.Id;
            }
            insert newTopMilestoneMap.values();
            
            //clone and insert sub milestone records
            Map<String, Milestone1_Milestone__c> newBottomMilestoneMap = Milestone1_Clone_Utility.cloneMilestonesIntoMap(bottomMilestones);
            for(Milestone1_Milestone__c newMS : newBottomMilestoneMap.values()){
                newMS.Project__c = newProj.Id;
                newMS.Parent_Milestone__c = newTopMilestoneMap.get(newMS.Parent_Milestone__c).Id;
            }
            insert newBottomMilestoneMap.values();
            //collect all milestones into one map
            Map<String, Milestone1_Milestone__c> allNewMilestoneMap = new Map<String, Milestone1_Milestone__c>();
            allNewMilestoneMap.putAll(newTopMilestoneMap);
            allNewMilestoneMap.putAll(newBottomMilestoneMap);            
            
            
            list<User_Story__c> userStoryList = new list<User_Story__c>([SELECT Milestone1_Milestone__c, Id, Name__c, Backlog__c, Feature_Request__c, (Select Id, Name__c, Backlog__c, Feature_Request__c, Milestone1_Milestone__c From Feature_Requests__r) FROM User_Story__c WHERE Milestone1_Milestone__c IN:milestones]);
            //list<User_Story__c> allUserStoryList = new list<User_Story__c>([SELECT Milestone1_Milestone__c, Id, Name__c, Backlog__c, Feature_Request__c, (Select Id From Feature_Requests__r) FROM User_Story__c WHERE Id IN:userStoryList OR Feature_Request__c IN:userStoryList]);
            //separate user story records into parents and subs
            /*List<User_Story__c> topUserStory = new List<User_Story__c>();
            List<User_Story__c> bottomUserStory = new List<User_Story__c>();
            for(User_Story__c oldUS : userStoryList){
                //if(oldUS.Feature_Requests__r == null || oldUS.Feature_Requests__r.isEmpty()){
                    topUserStory.add(oldUS);
                //} else {
                	for(User_Story__c childUS : oldUS.Feature_Requests__r){
                		bottomUserStory.add(childUS);
                	}
                    //bottomUserStory.add(oldUS);
                //}
            }*/
            List<Map<String, Object>> userStoryTree = new List<Map<String, Object>>();
            for(User_Story__c uStory : userStoryList)
            {
            	Map<String, Object> userStory = new Map<String, Object>();
            	userStory.put('userStory',uStory);
            	List<Map<String, Object>> children = new List<Map<String, Object>>();
                for(User_Story__c child : uStory.Feature_Requests__r)
                {
                	List<User_Story__c> aChild = new List<User_Story__c>();
                	aChild.add(child); 
                	children.add(Milestone1_Clone_Utility.getUserListChildren(aChild));
                }
            	userStory.put('children',children);
            	userStoryTree.add(userStory);
            }
            system.debug('userStoryTree>>>>>>>>>>>' + userStoryTree);
            Map<String, User_Story__c> recMap = new Map<String, User_Story__c>();
            Milestone1_Clone_Utility.cloneUserStoryIntoMap2(userStoryTree, recMap, allNewMilestoneMap, null, 1);
            system.debug('<<<<<<<<<recMap'+ recMap);
            /*system.debug('topUserStory>>>>>>>>>>>' + topUserStory);
            system.debug('bottomUserStory>>>>>>>>>>>' + bottomUserStory);
            //clone and insert top user story records
            Map<String, User_Story__c> newTopUserStoryMap = Milestone1_Clone_Utility.cloneUserStoryIntoMap(topUserStory);
            for(User_Story__c newUS : newTopUserStoryMap.values()){
            	if(allNewMilestoneMap.get(newUS.Milestone1_Milestone__c) != null)
                	newUS.Milestone1_Milestone__c = allNewMilestoneMap.get(newUS.Milestone1_Milestone__c).Id;
            }
            insert newTopUserStoryMap.values();
            
            //clone and insert sub user Story records
            Map<String, User_Story__c> newBottomUserStoryMap = Milestone1_Clone_Utility.cloneUserStoryIntoMap(bottomUserStory);
            for(User_Story__c newUS : newBottomUserStoryMap.values()){
            	if(allNewMilestoneMap.get(newUS.Milestone1_Milestone__c) != null)
                	newUS.Milestone1_Milestone__c = allNewMilestoneMap.get(newUS.Milestone1_Milestone__c).Id;
                if(newTopUserStoryMap.get(newUS.Feature_Request__c) != null)
                	newUS.Feature_Request__c = newTopUserStoryMap.get(newUS.Feature_Request__c).Id;
            }
            insert newBottomUserStoryMap.values();
            //collect all milestones into one map
            Map<String, User_Story__c> allNewUserStoryMap = new Map<String, User_Story__c>();
            allNewUserStoryMap.putAll(newTopUserStoryMap);
            allNewUserStoryMap.putAll(newBottomUserStoryMap);*/
            
            /*// To clone User stories
            map<Id,User_Story__c> objUS = new map<Id,User_Story__c>([SELECT Milestone1_Milestone__c, Id, Name__c, Backlog__c FROM User_Story__c WHERE Milestone1_Milestone__c IN:milestones]);
            Map<String, User_Story__c> newUserStoryMap = Milestone1_Clone_Utility.cloneUserStoryIntoMap(objUS.values());
            for(User_Story__c newUS : newUserStoryMap.values()){
                newUS.Milestone1_Milestone__c = allNewMilestoneMap.get(newUS.Milestone1_Milestone__c).Id;
            }
            insert newUserStoryMap.values();
            list<User_Story__c> toUserStoryInsert = new list<User_Story__c>();
            for(User_Story__c us:objUS.values()){
            	User_Story__c tmpUserStory = us.clone(false);
            	tmpUserStory.Milestone1_Milestone__c = allNewMilestoneMap.get(us.Milestone1_Milestone__c).Id;
            	toUserStoryInsert.add(tmpUserStory);
            }
            if(!toUserStoryInsert.isEmpty()){
            	insert toUserStoryInsert;
        	}
        	for(User_Story__c us:toUserStoryInsert){
        		if(objUS.get(us.Id) != null){
        			for(Milestone1_Task__c t:objUS.get(us.Id).Tasks__r){
		        		t.User_Story__c = us.Id;
		        		toTaskInsert.add(t.clone(false));
		        	}
        		}	        	  
        	} 
        	if(!toTaskInsert.isEmpty()){
        		insert toTaskInsert;
    		}*/
    		 
            //clone and insert task records
            List<Milestone1_Task__c> newTasks = Milestone1_Clone_Utility.cloneTasksIntoList(tasks);
            for(Milestone1_Task__c newTask : newTasks){
                newTask.Project_Milestone__c = allNewMilestoneMap.get(newTask.Project_Milestone__c).Id;
                if(recMap.get(newTask.User_Story__c) != null){
                	system.debug('<<<<<<recMap.get(newTask.User_Story__c).Id'+ recMap.get(newTask.User_Story__c).Id);
                	newTask.User_Story__c = recMap.get(newTask.User_Story__c).Id;
                }
                /*if(allNewUserStoryMap.get(newTask.User_Story__c) != null){
                	newTask.User_Story__c = allNewUserStoryMap.get(newTask.User_Story__c).Id;
                }*/
            }
            insert newTasks;
            
            //direct user to cloned project's detail page
            return new ApexPages.StandardController(newProj).view();
         
        }catch(Exception e){
            ApexPages.addMessages(e); //show save error(s) on the visualforce page
            Database.rollback(preSave); //rollback any completed saves if the transaction has errors
        }
        return pageReference;
    }

}