HDL ANT Deployment Package/retrieveUnpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>TBD</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A general description of the milestone.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>When should this milestone kickoff?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A general description of the project.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>What date should this project start?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Projects1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The current status of the project.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planning</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>MPM Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MPM Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PM_Status__c.object
<CustomObject>
    <description>Project Management Status Reporting object</description>
    <fields>
        <fullName>MPM_Project__c</fullName>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>PM Status</relationshipLabel>
        <relationshipName>PM_Status</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status_Summary__c</fullName>
        <label>Status Summary</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>PM Status</label>
    <nameField>
        <displayFormat>S-{00000000}</displayFormat>
        <label>Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PM Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Relationship_Status__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationship Status</relationshipLabel>
        <relationshipName>Relationship_Status</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status_Summary__c</fullName>
        <label>Status Summary</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yellow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Red</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Relationship Status</label>
    <nameField>
        <displayFormat>RS-{000000}</displayFormat>
        <label>Relationship Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationship Status</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Risk_and_Issues__c.object
<CustomObject>
    <description>Information about Risks on the project</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MPM_Project__c</fullName>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipName>Risks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Risk and Issue</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Risks and Issues</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/GeneratedReport.cls
public with sharing class GeneratedReport {
    
    public List<String> projectIdList{get; set;}    
    public list<ProjectM> objProjectM {get;set;}
    
    public GeneratedReport(){
        objProjectM = new list<ProjectM>();
        if(apexpages.currentpage().getparameters().get('selectedProjectdIds') != null && apexpages.currentpage().getparameters().get('selectedProjectdIds').trim() != ''){
            projectIdList = apexpages.currentpage().getparameters().get('selectedProjectdIds').split(',');          
            try{
                List<Milestone1_Project__c> mileStoneList = [SELECT Account__r.Name, Status__c,   
                            Account__r.Owner.Name, Opportunity__r.Project_Manager__r.Name,
                            Kickoff__c, Deadline__c, Name,
                            (Select Name, Status_Summary__c, Status__c, LastModifiedDate, LastModifiedBy.Name FROM PM_Status__r order by LastModifiedDate desc),
                            (Select  Description__c FROM Risks__r),
                            (Select Name, Deadline__c, Kickoff__c FROM Project_Milestones__r order by Kickoff__c desc)
                            FROM Milestone1_Project__c m WHERE Id IN :projectIdList order by Opportunity__r.Project_Manager__r.LastName];
                            
                for(Milestone1_Project__c mileStone : mileStoneList){
                    list<Milestone1_Milestone__c> currentMileStones = new list<Milestone1_Milestone__c>();
                    list<Milestone1_Milestone__c> nextMileStones = new list<Milestone1_Milestone__c>();
                    for(Milestone1_Milestone__c currentMileStone : mileStone.Project_Milestones__r){
                        if(System.TODAY() >= currentMileStone.Kickoff__c && System.TODAY() <= currentMileStone.Deadline__c){
                            currentMileStones.add(currentMileStone);
                        }
                        else if(currentMileStone.Kickoff__c >= System.TODAY()){
                            nextMileStones.add(currentMileStone);
                        }                       
                    }
                    
                    list<Relationship_Status__c> relationshipStatus = new list<Relationship_Status__c>();
                    list<Account> accountList;
                    if(mileStone.Account__c != null){
                        accountList = [SELECT Name, (SELECT Id, Status_Summary__c, Status__c FROM Relationship_Status__r order by CreatedDate desc) FROM Account WHERE ID =: mileStone.Account__c LIMIT 1];
                    }
                    if(accountList != null && !accountList.isEmpty()){
                        relationshipStatus = accountList.get(0).Relationship_Status__r;
                    }
                    objProjectM.add(new ProjectM(mileStone, mileStone.Risks__r, currentMileStones, nextMileStones, mileStone.PM_Status__r, relationshipStatus));
                }
            }
            catch(Exception e){
                
            }           
        }
        
    }
    
    public class ProjectM{
        public Milestone1_Project__c objMilestone1Project{get;set;}     
        public list<Risk_and_Issues__c> objRisk {get;set;}
        public list<Milestone1_Milestone__c> objCurrentMilestone {get;set;}
        public list<Milestone1_Milestone__c> objNextMilestone {get;set;}
        public list<PM_Status__c> objPMStatus {get;set;}
        public list<Relationship_Status__c> objRelationshipStatus {get;set;}
        public ProjectM(Milestone1_Project__c objMilestone1Project, list<Risk_and_Issues__c> objRisk, list<Milestone1_Milestone__c> objCurrentMilestone,
                        list<Milestone1_Milestone__c> objNextMilestone, list<PM_Status__c> objPMStatus, list<Relationship_Status__c> objRelationshipStatus){
            this.objMilestone1Project = objMilestone1Project;           
            //this.objRisk = objRisk;
            this.objCurrentMilestone = objCurrentMilestone;
            this.objNextMilestone = objNextMilestone;
            this.objPMStatus = objPMStatus;
            this.objRelationshipStatus = objRelationshipStatus;
        }
    }
}