HDL ANT Deployment Package/retrieveUnpackaged/objects/Order_Choice__c.object
<CustomObject>
    <label>Order Choice</label>
    <nameField>
        <label>Order Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HDL ANT Deployment Package/retrieveUnpackaged/objects/Profile__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>to which Practice should this profile be related</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Profiles</relationshipLabel>
        <relationshipName>Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Baseline</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Followup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Template</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HDL ANT Deployment Package/retrieveUnpackaged/objects/Profile_Order_Choice__c.object
<CustomObject>
    <fields>
        <fullName>Order_Choice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Choice</label>
        <referenceTo>Order_Choice__c</referenceTo>
        <relationshipLabel>Profile Order Choices</relationshipLabel>
        <relationshipName>Profile_Order_Choices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Profile</label>
        <referenceTo>Profile__c</referenceTo>
        <relationshipLabel>Profile Order Choices</relationshipLabel>
        <relationshipName>Profile_Order_Choices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Profile Order Choice</label>
    <nameField>
        <label>Profile Order Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profile Order Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DBUtility.cls
public with sharing class DBUtility {
	/*To get all Profile__c having type = template*/
	public static list<Profile__c> getProfileHavingTypeTemplate(){
		return new list<Profile__c>([Select Name,Type__c,Account__r.name From Profile__c  where type__C='Template']);
	}
	/**/
	public static list<Profile_Order_Choice__c> getProfileOrderChoice(){
		return new list<Profile_Order_Choice__c>([SELECT Name FROM Profile_Order_Choice__c]);
	}
	/*To get all Profile__c BY ID*/
	public static list<Profile__c> getProfileById(list<String> profileIds){
		return new list<Profile__c>([Select Name,Type__c,Account__r.name From Profile__c  where id IN:profileIds]);
	}
	/**/
	public static list<Profile__c> getProfileandOrderChoiceBypId(list<String> profileIds){
		return new list<Profile__c>([Select Account__c, (Select Id, OwnerId, Name, Order_Choice__c, Profile__c From Profile_Order_Choices__r) From Profile__c  where id IN:profileIds]);
	}
	/*
		@Description: To get profile and its all order choice by profile Id
		@Param: ProfileId 
	*/
	public static list<Profile__c> getProfileandOrderChoiceBypId(String profileId){
		return new list<Profile__c>([Select Name,type__c,Account__r.Name,Account__c, (Select Id, OwnerId, Name, Order_Choice__c, Profile__c From Profile_Order_Choices__r) From Profile__c  where id =:profileId]);
	}
	/*
	     @Description:-To get all Profile Order Choices  
	*/
	public static list<Profile_Order_Choice__c> getProfileOrder(){
		return new list<Profile_Order_Choice__c>([SELECT Name FROM Profile_Order_Choice__C  ]);
	}
}