HDL ANT Deployment Package/retrieveUnpackaged/objects/Profile__c.object
<CustomObject>
    <label>Profile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HDL ANT Deployment Package/retrieveUnpackaged/objects/Profile_Order_Choice__c.object
<CustomObject>
    <fields>
        <fullName>Profile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Profile</label>
        <referenceTo>Profile__c</referenceTo>
        <relationshipLabel>Profile Order Choices</relationshipLabel>
        <relationshipName>Profile_Order_Choices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Profile Order Choice</label>
    <nameField>
        <label>Profile Order Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profile Order Choices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewProfileAndSearchController.cls
/*
** Module Name   : NewProfileAndSearchController
** Description   : 
** Throws        : 
** Calls         : 
** Test Class    : 
** 
** Organization  : 
**
** Revision History:-
** Version  Date        Author    WO#         Description of Action
**                   Atulit Gupta      
**********************************************************************************************************************************************************/

public with sharing class NewProfileAndSearchController {
    //Variable Declaration  
    public Profile__c profObj {get;set;}
    public String searchInput {get;set;}
    public list<ProfileOrderChoice> objProfileOrderChoice{get;set;}
    
    // Constructor
    public NewProfileAndSearchController(){
        profObj = new Profile__c();
        objProfileOrderChoice = new list<ProfileOrderChoice>();
        for(Profile_Order_Choice__c obj : DBUtility.getProfileOrder()){
            objProfileOrderChoice.add(new ProfileOrderChoice(obj));
        }
    }
    
    
    public class ProfileOrderChoice{
        public boolean isAdded {get;set;}
        public Profile_Order_Choice__c objProfileOrder {get;set;}
        public ProfileOrderChoice(Profile_Order_Choice__c objProfileOrder){
            isAdded = false;
            this.objProfileOrder = objProfileOrder;
        }
    
    
    
    }
}